---
- hosts: all
  become: true
  pre_tasks:

  - name: Install Update (Ubuntu)
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
    
  - name: Update repository index (CentOS)
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"
     

  - name: start nagios in Centos
    tags: centos,apache,httpd,nagios
    service:
      name: httpd
      state: started
    when: ansible_distribution == "Centos"

- hosts: all
  become: true
  roles:
    - enterprise
    - monitor

- hosts: all
  become: true
  tasks:

  - name: Creating Banner Motd in Ubuntu
    debug:
      msg: "Ansible Managed node by Marquez"
    when: ansible_distribution == "Ubuntu"

  - name: Creating Banner Motd in CentOS
    debug:
      msg: "Ansible Managed node by Marquez"
    when: ansible_distribution == "CentOS"
